### PR TITLE
Add Binder support

### LINKED ISSUE #17: Add Binder support
Hi @glouppe. A few people on ATLAS are trying to reproduce the results of this repo and so to make it easier I thought I would just Binderize it &mdash; which I'm in the process of doing now (mostly just pinning dependencies due to Theano being used and deprecation of APIs since publication).

It was clear from the comment in [`Jets.ipynb`](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/Jets.ipynb) that the HDF5 datasets being used were the ones at http://www.igb.uci.edu/~pfbaldi/physics/data/hepjets/highlevel/ which would need to be downloaded, but [in `jets.py` there is ](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/jets.py#L16)

```python
# Prepare data
fd = open("jets-pile.pickle", "rb")
``` 

I'm assuming that `jets-pile.pickle` is just the pickling the output of

```python
X_train, X_test, y_train, y_test, z_train, z_test = train_test_split(X, y, z, test_size=25000, random_state=1, stratify=strates)
```
in [`Jets.ipynb`](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/Jets.ipynb), correct? Nothing else was done?

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #17 

This PR adds Binder support by [installing all the required Python libraries necessary to run all the code in the repo with `conda`'s `pip` through the `environment.yml` or through `conda` itself for `mkl`](https://mybinder.readthedocs.io/en/latest/config_files.html#environment-yml-install-a-python-environment) (what would be the `requirements.txt`). As the Theano backend for Keras is meant to be used with this repo the default `$HOME/.keras/keras.json` config file that is generated the first time Keras is used must be changed to use Theano instead of TensorFlow. This is done by using the `jsonpatch` CLI to use [JSON Patch](http://jsonpatch.com/) to update the `$HOME/.keras/keras.json` in `postBuild`. Additionally, to avoid warnings from Theano about BLAS [Binder installs `libblas-dev` with `apt-get`](https://mybinder.readthedocs.io/en/latest/config_files.html#apt-txt-install-packages-with-apt-get).

To have the Jet Substructure datasets available from ['Jet Substructure Classification in High-Energy Physics with Deep Neural Networks'](http://www.igb.uci.edu/~pfbaldi/physics/data/hepjets/readme.txt) which are used in this repo for `Jets.ipynb` and `jets.py` the relevant HDF5 files are downloaded from the supporting UC Irvine website in `postBuild` and moved to the locations required by the notebook. `Jets.ipynb` is also amended to include a step that pickles the relevant data for `jets.py` to use.

Additionally, a launch Binder badge is added to the `README` that launches directly into the `Toy.ipynb` Jupter notebook instead of the Jupyter server browser as the Jets notebook is long enough and requires multiple runnings of `jets.py` such that it isn't well suited for Binder.

For a demo of what this looks like you can click on this badge which will launch the Binder ~~of my fork~~ (**edit:** as I deleted my branch this is now the Binder of `master`): [Binder](https://mybinder.org/v2/gh/glouppe/paper-learning-to-pivot/master?filepath=code%2FToy.ipynb)

This is enough to get the notebooks to run. However, given API deprecations there are some warnings that arise, but beyond being ugly to look at they shouldn't affect the performance.

### CODE REVIEW

**Comment by glouppe** [comment]
Tell me when you want this be reviewed and merged. Thanks for the help!

**Comment by matthewfeickert** [comment]
> Tell me when you want this be reviewed and merged

@glouppe Will do! I will probably wait until tomorrow to try and make things a bit more efficient, but I'll ping you when this is ready for review.

**Comment by matthewfeickert** [comment]
@glouppe As this set of commits accomplishes the goal of getting things to run in Binder then I think this is ready for review.

The only thing that I will note is that if you launch `Toy.ipynb` and do Restart & Run All you don't recover what is [shown in the current `Toy.ipynb`](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/Toy.ipynb). Reproducing similar results is a different story then providing a sufficient runtime environment though, and as I haven't taken the time  to look more thoroughly at the notebook I'm not sure if there is some obvious reason for this given the code.

Let me know your thoughts and any requested edits (but obviously no rush on either :slightly_smiling_face:).

**Comment by glouppe** [comment]
Thanks a lot Matthew! This works great :)

**Pull request merged**
